services:
  postgres:
    image: postgres:16
    container_name: nest-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: shop

    ports:
      - "5432:5432"